name: loot_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  get: ^4.7.2
  get_storage: ^2.1.1
  http: ^1.4.0
  intl: ^0.20.2
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logos/ 
  fonts:
    - family: OpenSans  # Nome da família da fonte que você usará no código
      fonts:
        # - asset: assets/fonts/Roboto-Regular.ttf
        # - asset: assets/fonts/Roboto-Italic.ttf
        #   style: italic
        # - asset: assets/fonts/Roboto-Bold.ttf
        #   weight: 700 # Bold
        # - asset: assets/fonts/Roboto-Light.ttf
        #   weight: 300 # Light
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700 # Bold
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300 # Light