name: loot_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  get: ^4.7.2
  get_storage: ^2.1.1
  http: ^1.4.0
  intl: ^0.20.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ 
  fonts:
    - family: Roboto  # Nome da família da fonte que você usará no código
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700 # Bold
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300 # Light