// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiP7NWqMM5SKjFM_Tj9rnNaGZO7TqYpXA',
    appId: '1:440977899070:web:890b547c4dfc124af5db6f',
    messagingSenderId: '440977899070',
    projectId: 'loot-app-e7eae',
    authDomain: 'loot-app-e7eae.firebaseapp.com',
    storageBucket: 'loot-app-e7eae.firebasestorage.app',
    measurementId: 'G-N6VZ1XSH7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDp0VdEUZje4rJ70C1jikCqccd9-16JLI',
    appId: '1:440977899070:android:473ef2841ea6dfb3f5db6f',
    messagingSenderId: '440977899070',
    projectId: 'loot-app-e7eae',
    storageBucket: 'loot-app-e7eae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEUnr21lG88mMq5XcTeD6Z4THUMPfHFSM',
    appId: '1:440977899070:ios:0b34900a20e2a06bf5db6f',
    messagingSenderId: '440977899070',
    projectId: 'loot-app-e7eae',
    storageBucket: 'loot-app-e7eae.firebasestorage.app',
    iosBundleId: 'com.example.lootApp',
  );
}
